version: "3"
services:

  db:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'password1'
      MYSQL_DATABASE: 'lyceedb'
      MYSQL_USER: 'lycee'
      MYSQL_PASSWORD: 'password1!'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/datasets:/datasets
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/volumes:/var/lib/mysql
#      - lycee-web-library-db:/var/lib/mysql

volumes:
  lycee-web-library-db:
